#!/bin/sh
set -e

lb config noauto \
    --distribution testing \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --debian-installer false \
    --memtest none \
    --iso-application "NakumiOS" \
    --iso-publisher "NakumiOS Project" \
    --iso-volume "NakumiOS 1.0" \
    "${@}"
