#!/bin/sh
set -e

lb config noauto \
    --distribution testing \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --debian-installer false \
    --memtest none \
    --linux-packages "linux-image" \
    --linux-flavours "amd64" \
    --mirror-bootstrap "http://deb.debian.org/debian" \
    --mirror-chroot-security "http://security.debian.org/debian-security" \
    --mirror-binary "http://deb.debian.org/debian" \
    --mirror-binary-security "http://security.debian.org/debian-security" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian" \
    --parent-mirror-chroot-security "http://security.debian.org/debian-security" \
    --parent-mirror-binary "http://deb.debian.org/debian" \
    --parent-mirror-binary-security "http://security.debian.org/debian-security" \
    --bootstrap-keyring debian-archive-keyring \
    --iso-application "NakumiOS" \
    --iso-publisher "NakumiOS Project" \
    --iso-volume "NakumiOS 1.0" \
    "${@}"
