#!/bin/bash
# generate-readme.sh - Generates README.md with build instructions,
# architecture details, and desktop screenshot.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="${PROJECT_DIR}/docs/RELEASE_NOTES.md"
README="${PROJECT_DIR}/README.md"

# Start with the header
cat > "${README}" << 'EOF'
# NakumiOS v1.0

A modern, lightweight Linux desktop operating system built on Debian Testing (Trixie).

EOF

# Add screenshot section (conditional on file existence)
if [ -f "${PROJECT_DIR}/docs/desktop-screenshot.png" ]; then
    cat >> "${README}" << 'EOF'
## Desktop Screenshot

![NakumiOS Desktop](docs/desktop-screenshot.png)

EOF
else
    cat >> "${README}" << 'EOF'
## Desktop Screenshot

> **Note:** Desktop screenshot is captured automatically by `make test-automation`,
> which boots the ISO in QEMU headlessly, waits for the Wayland compositor to start,
> and runs `grim` via the `nakumi-screenshot.service` systemd oneshot to extract
> the framebuffer image through a 9p virtfs share.

<!-- Screenshot will appear here when generated by the automated pipeline -->
<!-- ![NakumiOS Desktop](docs/desktop-screenshot.png) -->

EOF
fi

# Add the main content (quoted heredoc - no variable expansion)
cat >> "${README}" << 'EOF'
## Features

- **Custom Wayland Compositor** (nakumi-wm) - Built with wlroots using the wlr_scene graph API
- **Qt6 Desktop Environment** - Panel, Launcher, and desktop shell using native Wayland protocols
- **Core Applications** - Terminal, File Manager, Text Editor, Settings
- **Modern Design** - Dark theme with purple accents, minimalist UI
- **VM Compatible** - Automatic software rendering fallback for VirtualBox/VMware/QEMU
- **PipeWire Audio** - Modern audio stack with WirePlumber session management
- **Auto-login** - Boots directly to desktop via greetd

## Architecture

```
┌─────────────────────────────────────────────────┐
│                NakumiOS Desktop                  │
├──────────┬──────────┬──────────┬────────────────┤
│ Panel    │ Launcher │ Terminal │  Apps (Qt6)     │
├──────────┴──────────┴──────────┴────────────────┤
│            nakumi-wm (wlroots compositor)        │
├─────────────────────────────────────────────────┤
│  Wayland │ PipeWire │  D-Bus  │ NetworkManager  │
├─────────────────────────────────────────────────┤
│              Linux Kernel (Debian Testing)       │
└─────────────────────────────────────────────────┘
```

## Architectural Audit Summary

This section documents the verified architectural vectors per the Lead Systems Architect code audit.

### Vector 1: Compositor Input & Focus Routing
- **xkbcommon keymap**: Compiled via `xkb_keymap_new_from_names()` in `server_new_keyboard()` (`nakumi-wm/src/main.c:310-315`)
- **Keyboard routing**: `keyboard_handle_key()` translates libinput→xkb keysyms, checks Super modifier for compositor bindings, else forwards via `wlr_seat_keyboard_notify_key()` (`main.c:263-289`)
- **Focus switching**: `focus_toplevel()` deactivates previous surface, raises scene node, calls `wlr_seat_keyboard_notify_enter()` with current keycodes+modifiers (`main.c:171-206`)

### Vector 2: Qt6 Wayland Native Extraction
- **Private header**: `#include <QtWaylandClient/private/qwaylandwindow_p.h>` (`layershellwindow.cpp:10`)
- **Surface extraction**: `dynamic_cast<QtWaylandClient::QWaylandWindow*>(m_window->handle())` → `wlSurface()` (`layershellwindow.cpp:110-117`)
- **CMake link**: `Qt6::WaylandClientPrivate` in `target_link_libraries` (`panel/CMakeLists.txt:113`)

### Vector 3: UDisks2 D-Bus Signature
- **Method call**: `QDBusMessage::createMethodCall(UDISKS2_SERVICE, devicePath, UDISKS2_FS, "Mount")` (`mountmanager.cpp:48-49`)
- **a{sv} construction**: `QVariantMap options; msg << QVariant::fromValue(options);` (`mountmanager.cpp:52-53`)
- **Async execution**: `QDBusPendingCallWatcher` on `asyncCall()` result (`mountmanager.cpp:55-59`)

### Vector 4: PTY Render Loop & UI Thread Safety
- **Separate thread**: `PtyReader` runs `poll()` loop in dedicated `QThread` (`terminalbackend.cpp:27-50`)
- **Batched output**: 4096-byte read buffer, 100ms poll timeout (`terminalbackend.cpp:29,36`)
- **SIGWINCH**: `ioctl(m_masterFd, TIOCSWINSZ, &ws)` in `updateWindowSize()` (`terminalbackend.cpp:212-220`)

### Vector 5: VM Resilience Logic
- **DMI detection**: Reads `/sys/class/dmi/id/product_name` for VirtualBox/VMware/QEMU/KVM/Bochs (`start-nakumi:27-34`)
- **systemd fallback**: `systemd-detect-virt -q` as secondary check (`start-nakumi:35-39`)
- **Software rendering**: Exports `WLR_RENDERER=pixman`, `LIBGL_ALWAYS_SOFTWARE=1`, `WLR_NO_HARDWARE_CURSORS=1` (`start-nakumi:52-57`)

### Vector 6: Automated Screenshot Pipeline
- **Guest script**: `/usr/bin/nakumi-screenshot` — waits for compositor, runs `grim`, saves to 9p virtfs mount
- **Systemd service**: `nakumi-screenshot.service` — oneshot triggered after `graphical.target`
- **Host target**: `make test-automation` — QEMU with 180s timeout, 9p share to `./docs/`, validates screenshot extraction

## Design Tokens

| Token       | Value     |
|-------------|-----------|
| Background  | `#1A1A24` |
| Accent      | `#6C5CE7` |
| Text        | `#E2E8F0` |
| Radius      | `12px`    |

## Build from Source

### Prerequisites

- Debian Testing (Trixie) or Ubuntu 24.04+
- `live-build`, `meson`, `cmake`, `ninja-build`
- Qt6 development packages
- wlroots development packages

### Build the ISO

```bash
# Build all components
make build-all

# Build the live ISO (requires root for live-build)
make iso
```

### Test in QEMU

```bash
# Launch in QEMU (interactive)
make run

# Automated testing with desktop screenshot capture
make test-automation
```

### Run Unit Tests

```bash
make test
```

### Create a GitHub Release

```bash
make publish
```

## Component Overview

| Component       | Language | Build System | Description                        |
|-----------------|----------|--------------|------------------------------------|
| nakumi-wm       | C        | Meson        | Wayland compositor (wlroots)       |
| nakumi-panel    | C++20    | CMake        | Bottom dock panel (layer-shell)    |
| nakumi-launcher | C++20    | CMake        | Fullscreen application launcher    |
| nakumi-term     | C++20    | CMake        | Terminal emulator (forkpty+poll)    |
| nakumi-files    | C++20    | CMake        | File manager (UDisks2 D-Bus)       |
| nakumi-edit     | C++20    | CMake        | Text editor (syntax highlighting)  |
| nakumi-settings | C++20    | CMake        | System settings (nmcli, wpctl)     |

## License

MIT License - See LICENSE for details.
EOF

echo "README.md generated."

# Also generate release notes
cat > "${OUTPUT}" << 'EOF'
## NakumiOS v1.0.0 Release

### What's New

- Initial release of NakumiOS
- Custom wlroots-based Wayland compositor with wlr_scene API
- Qt6 Desktop Environment with layer-shell panel and application launcher
- Core applications: Terminal, File Manager, Text Editor, Settings
- Debian Testing (Trixie) base with live-build
- PipeWire audio with WirePlumber
- Automatic software rendering fallback for VMs
- Auto-login via greetd
- Automated screenshot pipeline via grim + 9p virtfs

### System Requirements

- x86_64 processor
- 2 GB RAM minimum (4 GB recommended)
- 4 GB disk space
- GPU with DRM/KMS support (or runs in software rendering mode)

### Checksums

See the accompanying `.sha256` file for ISO integrity verification.
EOF

echo "RELEASE_NOTES.md generated."
